In [2]:
### Kaggle competition ###
import pandas as pd

In [3]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np #from pandas.api.types 
# import is_string_dtype, is_numeric_dtype

In [5]:
train_df = pd.read_csv("train.csv", index_col='index')
df = train_df.reset_index()
df

,index,session_id,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,0,20090312431273200,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4
1,1,20090312431273200,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
2,2,20090312431273200,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
3,3,20090312431273200,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
4,4,20090312431273200,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,1600,22100221145014656,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296942,1601,22100221145014656,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296943,1602,22100221145014656,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296944,1603,22100221145014656,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296945,1604,22100221145014656,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22

In [6]:
train_df

,session_id,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
index,,,,,,,,,,,,,,,,,,,
0,20090312431273200,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4
1,20090312431273200,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
2,20090312431273200,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
3,20090312431273200,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
4,20090312431273200,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,22100221145014656,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
1601,22100221145014656,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
1602,22100221145014656,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
1603,22100221145014656,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
1604,22100221145014656,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22

In [7]:
train_df.columns.tolist()

['session_id',
 'elapsed_time',
 'event_name',
 'name',
 'level',
 'page',
 'room_coor_x',
 'room_coor_y',
 'screen_coor_x',
 'screen_coor_y',
 'hover_duration',
 'text',
 'fqid',
 'room_fqid',
 'text_fqid',
 'fullscreen',
 'hq',
 'music',
 'level_group']

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26296946 entries, 0 to 1604
Data columns (total 19 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   elapsed_time    int64
 2   event_name      object
 3   name            object
 4   level           int64
 5   page            float64
 6   room_coor_x     float64
 7   room_coor_y     float64
 8   screen_coor_x   float64
 9   screen_coor_y   float64
 10  hover_duration  float64
 11  text            object
 12  fqid            object
 13  room_fqid       object
 14  text_fqid       object
 15  fullscreen      int64
 16  hq              int64
 17  music           int64
 18  level_group     object
dtypes: float64(6), int64(6), object(7)
memory usage: 3.9+ GB

In [9]:
# Expressing train columns in percentage of missing information.
df = train_df.isnull().sum().sort_values(ascending=False)
per_1 = train_df.isnull().sum() / len(train_df)*100
# Casting series to a new dataframe
per_2 = (round(per_1, 1)).sort_values(ascending=False)
missing_data = pd.concat([df,per_2], axis=1,keys=['number','percentage_null'])
missing_data.head(25)

                  number  percentage_null
page            25732402             97.9
hover_duration  24294702             92.4
text            16679807             63.4
text_fqid       16679702             63.4
fqid             8274415             31.5
screen_coor_y    2073272              7.9
room_coor_x      2073272              7.9
room_coor_y      2073272              7.9
screen_coor_x    2073272              7.9
room_fqid              0              0.0
music                  0              0.0
hq                     0              0.0
fullscreen             0              0.0
session_id             0              0.0
elapsed_time           0              0.0
level                  0              0.0
name                   0              0.0
event_name             0              0.0
level_group            0              0.0

In [19]:
train_label = pd.read_csv("train_labels.csv", index_col=False)
train_label.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424116 entries, 0 to 424115
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   session_id  424116 non-null  object
 1   correct     424116 non-null  int64
dtypes: int64(1), object(1)
memory usage: 6.5+ MB

In [20]:
train_label[['session_id', 'question']] = train_label['session_id'].str.split('_', 1, expand=True)
train_label

               session_id  correct question
0       20090312431273200        1       q1
1       20090312433251036        0       q1
2       20090312455206810        1       q1
3       20090313091715820        0       q1
4       20090313571836404        1       q1
...                   ...      ...      ...
424111  22100215342220508        1      q18
424112  22100215460321130        1      q18
424113  22100217104993650        1      q18
424114  22100219442786200        1      q18
424115  22100221145014656        1      q18

[424116 rows x 3 columns]

In [24]:
train_df["fqid"].unique()

array(['intro', 'gramps', 'teddy', 'photo', nan, 'notebook',
       'retirement_letter', 'tobasement', 'janitor', 'toentry',
       'groupconvo', 'report', 'boss', 'wells', 'directory',
       'tocollection', 'cs', 'tunic', 'tunic.hub.slip', 'tostacks',
       'outtolunch', 'tocloset', 'tomap', 'tunic.historicalsociety',
       'tunic.kohlcenter', 'plaque', 'plaque.face.date', 'togrampa',
       'tunic.capitol_0', 'chap1_finale', 'chap1_finale_c',
       'tocloset_dirty', 'what_happened', 'trigger_scarf',
       'trigger_coffee', 'tunic.capitol_1', 'tofrontdesk', 'archivist',
       'magnify', 'tunic.humanecology', 'worker', 'businesscards',
       'businesscards.card_0.next', 'businesscards.card_1.next',
       'businesscards.card_bingo.next', 'businesscards.card_bingo.bingo',
       'tohallway', 'tunic.drycleaner', 'logbook', 'logbook.page.bingo',
       'tunic.library', 'tomicrofiche', 'reader', 'reader.paper0.next',
       'reader.paper1.next', 'reader.paper2.bingo', 'wellsbadge',
       'journals', 'journals.hub.topics', 'journals.pic_0.next',
       'journals.pic_1.next', 'journals.pic_2.bingo', 'chap2_finale_c',
       'ch3start', 'seescratches', 'tocage', 'glasses',
       'directory.closeup.archivist', 'key', 'unlockdoor',
       'confrontation', 'savedteddy', 'tocollectionflag',
       'groupconvo_flag', 'tunic.capitol_2', 'tunic.wildlife', 'coffee',
       'crane_ranger', 'remove_cup', 'expert', 'tracks',
       'tracks.hub.deer', 'tunic.flaghouse', 'flag_girl', 'colorbook',
       'reader_flag', 'reader_flag.paper0.next',
       'reader_flag.paper1.next', 'reader_flag.paper2.bingo',
       'archivist_glasses', 'journals_flag',
       'journals_flag.hub.topics_old', 'journals_flag.hub.topics',
       'journals_flag.pic_0.bingo', 'journals_flag.pic_0.next',
       'chap4_finale_c', 'block_tocollection', 'reader.paper2.next',
       'journals.pic_2.next', 'lockeddoor', 'reader.paper2.prev',
       'reader.paper0.prev', 'reader_flag.paper1.prev',
       'journals_flag.pic_0_old.next', 'journals_flag.pic_1_old.next',
       'reader.paper1.prev', 'block_0', 'journals_flag.pic_1.bingo',
       'block_magnify', 'journals_flag.pic_1.next', 'doorblock',
       'journals_flag.pic_2.bingo', 'journals_flag.pic_2.next',
       'door_block_clean', 'door_block_talk', 'block',
       'reader_flag.paper2.next', 'block_tomap2',
       'reader_flag.paper0.prev', 'journals_flag.pic_2_old.next',
       'need_glasses', 'block_nelson', 'block_tomap1',
       'reader_flag.paper2.prev', 'block_badge', 'fox', 'block_badge_2',
       'block_1', 'chap2_finale'], dtype=object)